# Site settings
title: Inf-2202 Concurrent and Data-Intensive Programming
# email: bjorn@cs.uit.no, einar@cs.uit.no
description: > # this means to ignore newlines until "baseurl:"
  Inf-2202 Concurrent and Data-Intensive Programming, fall 2015, University of Tromsø. 
baseurl: "/inf-2202" # the subpath of your site, e.g. /blog/
url: "https://github.com/uit-inf-2202/syllabus" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
